site_name: Scripta Developer Docs
site_url: https://jxxcarlson.github.io/docs-scripta-app
docs_dir: 'docs-scripta-app'
dev_addr: '127.0.0.1:8202'

theme: material


nav:
  - Home: 'index.md'
  - Mkdocs Info: 'mkdocs-info.md'
  - Lamdera: 'lamdera.md'
  - The L0 Markup Language: 'L0.md'
  - Making a New Document: 'newdocs.md'
  - Opening a Document: 'openDoc.md'
  - Loading data into a document: 'data.md'
  - Document Index: 'documentIndex.md'
  - Collection Documents: 'collectionDocs.md'
  - Smart Folders: 'smartfolders.md'
  - Search: 'search.md'
  - Codemirror: 'codemirror.md'
  - PDF Server: 'pdfServer.md'
  - Stats: 'stats.md'


